___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [7]:
print(f'Версія - {np.__version__}, Конфігурацію: {np.show_config()}', sep = '\n\n')

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/User

____________________

Створити вектор з 10 елементів, заповнений одиницями:

In [8]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

____________________

Створити вектор із значеннями від 0 до 10:

In [20]:
# делала до 10 включительно. 
version1 = np.array([i for i in range(11)])
version2 = np.arange(0,10)
print(version1, version2, sep = '\n')

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]


____________________

Створити матрицю 5 на 5, заповнену нулями:

In [21]:
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

____________________

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:


In [30]:
#Заповнити вектор з 20 елементів випадковими цілими числами
np.random.seed(1)
vector = np.random.randint(0,10,20)
vector

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9, 2, 4, 5, 2, 4, 2, 4, 7, 7, 9])

In [67]:
# індекси ненульових елементів. два способоа
version_1, = np.where(vector !=  0)
version_2 = np.nonzero(vector)
print(version_1, f'type of version_1 = {type(version_1)}', version_2, f'type of version_2 = {type(version_2)}', sep = '\n\n')

[ 0  1  2  3  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

type of version_1 = <class 'numpy.ndarray'>

(array([ 0,  1,  2,  3,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19], dtype=int64),)

type of version_2 = <class 'tuple'>


____________________

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [37]:
print(f'вектор із попередньої задачі:\n \
   середнє значення: {vector.min()},\n    медіана: {np.median(vector)},\n    стандартне відхилення: {vector.std().round(2)}')

вектор із попередньої задачі:
    середнє значення: 0,
    медіана: 5.0,
    стандартне відхилення: 2.87


____________________

Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [144]:
np.random.seed(2)
matrix1 = np.random.randint(0,10, (4, 2))
matrix2 = np.random.randint(0,100, (2, 2))
m1_m2 = np.dot(matrix1, matrix2)
print(matrix1, matrix2, m1_m2, sep = '\n\n')

[[8 8]
 [6 2]
 [8 7]
 [2 1]]

[[95 75]
 [85 47]]

[[1440  976]
 [ 740  544]
 [1355  929]
 [ 275  197]]


____________________

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [145]:
#Результуючу матрицю із попередньої задачі перетворити у вектор
print(np.reshape(m1_m2, np.size(m1_m2), 1))

#Знайти мінімальне та максимальне значення.
print('\n' f'max - {np.max(m1_m2)}, min - {np.min(m1_m2)}')

[1440  740 1355  275  976  544  929  197]

max - 1440, min - 197


In [146]:
# Максимальне значення замінити на 0:
print('Исходная матрица:', '\n', m1_m2, '\n\n')

from numpy import where
i,j = where(m1_m2 == np.max(m1_m2))
m1_m2[i,j] = 0

print('Матрица с заменой:', '\n',  m1_m2)

Исходная матрица: 
 [[1440  976]
 [ 740  544]
 [1355  929]
 [ 275  197]] 


Матрица с заменой: 
 [[   0  976]
 [ 740  544]
 [1355  929]
 [ 275  197]]


____________________

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [147]:
m1_m2

array([[   0,  976],
       [ 740,  544],
       [1355,  929],
       [ 275,  197]])

In [202]:
#пройдём по каждой строке матрицы, начиная с 1й строки (пайтоновой)
#считаем корееляцию первой строки с каждой последующей. и потом с результирующей ковариационой матрицы выбираем нужный элемент.
for i in range(1, m1_m2.shape[0]): 
    print(np.corrcoef(m1_m2[0], m1_m2[i])[1,0]) 
    

 


-1.0
-1.0
-1.0


In [ ]:
#Получилось непоказательным, что все строки имеют одинаковую корреляцию, поэтому я применила расчёт корреляции к матрице
#со следующего задания

In [204]:
matrix2 = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

for i in range(1, matrix2.shape[0]): 
    print(np.corrcoef(matrix2[0], matrix2[i])[1,0]) 

-0.9986254289035237
-0.2773500981126145


____________________

Дано матрицю. Знайти ранг матриці:

In [291]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])


In [292]:
np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [293]:
np.linalg.det(a).round(0)

440.0

Знайти власні значення та власні вектори матриці: 

In [295]:
np.linalg.eigh(a)

(array([-14.30540864,  -4.34740072,  23.65280936]),
 array([[ 0.15315575,  0.88160309,  0.44645191],
        [ 0.63674998, -0.43353159,  0.6376518 ],
        [-0.75570681, -0.18661821,  0.62775861]]))

____________________

Знайдіть число, що найчастіше зустрічається в масиві:

In [231]:
np.random.seed(10)
a = np.random.randint(0,10,50)
a

array([9, 4, 0, 1, 9, 0, 1, 8, 9, 0, 8, 6, 4, 3, 0, 4, 6, 8, 1, 8, 4, 1,
       3, 6, 5, 3, 9, 6, 9, 1, 9, 4, 2, 6, 7, 8, 8, 9, 2, 0, 6, 7, 8, 1,
       7, 1, 4, 0, 8, 5])

In [286]:
number, count = np.unique(a, return_counts=True) # получаем два массива с сотрированными элементами и их количеством входждений.
int(number[np.where(count == count.max())])
# в кол-ве вхождений находим макс кол-во, получаем индекс этого значения. 
#И в массиве с самими исходными цифрами берём элемент по точно такому же индексу (как и в кол-ве).

8

______________________________________

Виведіть лише парні числа, що діляться на 5:

In [208]:
# !!! ПРИМЕЧАНИЕ
#a = np.random.randint(0,10,50) - в этом списке не может быть вариантов, которые удовлетворяют заданому условию,
# потому что генерится список с числами до 10, т.е. максимальное число в списке будет = 9, а ближайшее число, 
# которое удовлетворяет  заданому условию это число 10 (что б было парное и при этом делилось на 5).
# Поэтому я поменяла диапазон в генерации матрицы (увеличила диапазон).
# было вот так a = np.random.randint(0,10,50)
np.random.seed(5)
a = np.random.randint(0,50,50)
a

array([35, 14, 47, 38, 16,  9,  8, 36, 39, 27, 48, 30, 16,  7, 12, 15, 49,
       39, 16, 27, 44, 13, 11,  1, 47, 30, 20, 22, 18,  9, 42, 41, 41,  1,
       18, 39, 16, 14,  5,  0, 16,  4, 46, 36, 41, 27, 31,  2,  4, 38])

In [205]:
even_devided5 = list(filter(lambda x: (x%2 == 0) & (x%3 == 0), a))
even_devided5

[36, 48, 30, 12, 30, 18, 42, 18, 0, 36]

______________________________________

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [175]:
a_equation = np.array([[2, 5],
             [1, -10]])
b_equation = np.array([1, 3])
print(np.linalg.solve(a_equation, b_equation))

[ 1.  -0.2]
